### Step 1: Import Libraries
Imports essential libraries for data manipulation `pandas`, `numpy` `matplotlib` `seaborn` `sklearn`). It also imports `pymongo` to connect Python to MongoDB database.

In [1]:
import pandas as pd
import numpy as np
import pymongo

### Step 2: Database Connection & Data Ingestion
Establishes a connection to your local MongoDB server.

In [16]:
client = pymongo.MongoClient("mongodb://localhost:27017/")
db = client["HousingDB"]
collection = db["US_Housing_Market"]
df = pd.read_csv('USA_Housing.csv')
print(list(df))

['Avg. Area Income', 'Avg. Area House Age', 'Avg. Area Number of Rooms', 'Avg. Area Number of Bedrooms', 'Area Population', 'Price', 'Address']

### Step 3: High Income Query
Queries the database for records where the neighborhood's average income is more than $80,000

In [17]:
query_income = collection.find({"Avg_Area_Income": {"$gt": 80000}}, {"_id": 0})
df_high_income = pd.DataFrame(list(query_income))
print({len(df_high_income)})
df_high_income.head()

{690}

,Avg_Area_Income,Avg_Area_House_Age,Avg_Area_Number_of_Rooms,Avg_Area_Number_of_Bedrooms,Area_Population,Price,Address
0,80175.754159,4.988408,6.104512,4.04,26748.428425,1.068138e+06,"06039 Jennifer Islands Apt. 443\nTracyport, KS..."
1,81885.927184,4.423672,8.167688,6.10,40149.965749,1.545155e+06,Unit 9446 Box 0958\nDPO AE 97025
2,80527.472083,8.093513,5.042747,4.10,47224.359840,1.707046e+06,"6368 John Motorway Suite 700\nJanetbury, NM 26854"
3,86294.999089,6.627457,8.011898,4.07,47560.775336,2.146925e+06,"030 Larry Park Suite 665\nThomashaven, HI 8794..."
4,82173.626076,4.018525,6.992699,2.03,38853.918066,1.125693e+06,"3599 Ramirez Springs\nJacksonhaven, AZ 72798"

### Step 4: Bedroom Query
Queries the database for real estate records where properties have exactly 3 bedrooms.

In [24]:
query2 = collection.find({"Avg_Area_Number_of_Bedrooms": 3.0}, {"_id": 0})
df_3_beds = pd.DataFrame(list(query2))
print({len(df_3_beds)})
df_3_beds.head()

{23}

,Avg_Area_Income,Avg_Area_House_Age,Avg_Area_Number_of_Rooms,Avg_Area_Number_of_Bedrooms,Area_Population,Price,Address
0,75046.848204,4.983085,8.877240,3.0,32468.031152,1.287325e+06,"PSC 8891, Box 6475\nAPO AP 28726-5123"
1,72107.428069,4.542306,6.981984,3.0,29981.346541,1.039518e+06,Unit 5105 Box 8178\nDPO AP 03939
2,56901.093772,6.805948,6.474248,3.0,13704.350754,7.870396e+05,"484 Adrian Circles\nAprilberg, OH 84325-9197"
3,65454.974226,4.443153,8.005585,3.0,47740.638991,1.144478e+06,18153 Michelle Street Apt. 150\nNorth Juliebur...
4,78095.352630,6.837193,7.119862,3.0,32346.434992,1.538923e+06,"165 Rebecca Run\nSouth Hannahport, LA 92436-6494"

### MongoDB Query - Income And Bedroom Query
Queries for houses with both conditions met
Average area income is greater than $70,000
Average number of bedrooms is 4 or more

In [22]:
query3 = collection.find({
    "Avg_Area_Income": {"$gt": 70000},
    "Avg_Area_Number_of_Bedrooms": {"$gte": 4.0}}, {"_id": 0})

df_combined = pd.DataFrame(list(query3))
print({len(df_combined)})
df_combined.head()

{1215}

,Avg_Area_Income,Avg_Area_House_Age,Avg_Area_Number_of_Rooms,Avg_Area_Number_of_Bedrooms,Area_Population,Price,Address
0,79545.458574,5.682861,7.009188,4.09,23086.800503,1.059034e+06,"208 Michael Ferry Apt. 674\nLaurabury, NE 3701..."
1,80175.754159,4.988408,6.104512,4.04,26748.428425,1.068138e+06,"06039 Jennifer Islands Apt. 443\nTracyport, KS..."
2,81885.927184,4.423672,8.167688,6.10,40149.965749,1.545155e+06,Unit 9446 Box 0958\nDPO AE 97025
3,80527.472083,8.093513,5.042747,4.10,47224.359840,1.707046e+06,"6368 John Motorway Suite 700\nJanetbury, NM 26854"
4,73091.866746,5.443156,8.517513,4.01,23929.524053,1.306675e+06,"2278 Shannon View\nNorth Carriemouth, NM 84617"